name: "Test Workflow"
on:
  push:

jobs:
  job-1:
    name: "My First Job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x"

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: "Restore packages"
        run: dotnet restore ./src/workflow-sandbox.sln -v n

      - name: "Build Solution"
        run: dotnet build ./src/workflow-sandbox.sln -v n --no-restore

      - name: "Run tests"
        run: dotnet test ./src/workflow-sandbox.sln -v n --no-build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: |
            bin/Debug
            !bin/Debug/*.Tests
          retention-days: 1
